### ISSUE TITLE
Potential EULA violation

### ISSUE THREAD

**Issue by fontpolice** [cssconfau/2014#24]
Dear cssconfau,

It has come to our attention through [FontFinder](http://www.fontfinder.io) that your hosting of transat_text_standard.woff in this _public_ repository could be a potential violation of the End User License Agreement (EULA) between yourself and the respective foundry.

We recommend that you [remove](https://github.com/blog/1545-deleting-files-on-github) the files to avoid further action.

Sincerely,
The Font Police

**Comment by toolmantim** [comment]
Fixed in c36a2d3faf0ffc0d8db724596ea8d7a79531ea67

**Comment by fontpolice** [comment]
Thank you for your cooperation.
